services:
  - type: web
    name: my-e-learning-backend
    env: node
    rootDir: backend/courses-pj
    buildCommand: "npm install"
    startCommand: "node app.js"
 
    plan: free
    region: oregon

  - type: web
    name: my-e-learning-frontend
    env: node
    rootDir: frontend/E-Learning-main
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    plan: free
    region: oregon
